---
title: "Faceoffs"
author: "Last update: 02.06.19"
output: html_document
---
Note: Current data is only THROUGH GAME 14. 
```{r, echo =FALSE, warning=FALSE, message=FALSE}
library(readxl)
library(DataComputing)
library(plotly)

faceoffs <- read_excel('ROUGH3.xlsx')

faceoffs$soi_f = factor(faceoffs$soi,
                        levels = c("L", "C", "R"))

res <- 
  faceoffs %>%
  group_by(game, res, plr) %>%
  summarise(avg_count = n())

poss <-
  faceoffs %>%
  group_by(game, poss, plr) %>%
  summarise(avg_count = n())

winsr <-
  res[res$res == "W", 1:4]

lossesr <-
  res[res$res == "L", 1:4]

winsp <-
  poss[poss$poss == "W", 1:4]

lossesp <-
  poss[poss$poss == "L", 1:4]

soires <-
  faceoffs %>%
  group_by(res, soi_f, plr) %>%
  summarise((avg_count = n()))
```

#Possession Success Rate by Player
```{r, echo =FALSE, warning=FALSE, message=FALSE}
ggplot(data = faceoffs, aes(x = reorder(plr, plr), fill = poss)) +
  geom_bar(stat = 'count')
```

#Possession Success Rate by Game
```{r, echo = FALSE, warning = FALSE, message = FALSE}
ggplot(data = faceoffs, aes(x = game, fill = poss)) +
  geom_bar(stat = 'count')
```

#Progression of Faceoffs Won by Game and Player
```{r, echo = FALSE, warning = FALSE, fig.width =8, fig.height = 7}
ggplot(data = winsr, 
       aes(x = game, 
           y = avg_count)) +
  geom_point() +
  facet_wrap(~plr, ncol = 5) +
  stat_smooth(method = lm)
```

#Progression of Faceoffs Lost by Game and Player
```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 7, fig.width = 8}
ggplot(data = lossesr,
       aes(x= game, y = avg_count)) +
  geom_point() +
  facet_wrap(~plr, ncol = 5) +
  stat_smooth(method = lm)
```

# Five Number Summary of Odds of Possession
```{r, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 7, fig.width = 8}
crutial19 <-
  filter(poss, plr == '19')
crutial10 <-
  filter(poss, plr == '10')

crutial <-
  full_join(crutial19, crutial10) %>%
  mutate(plr = as.character(plr))

crutial %>%
  ggplot(aes(x = plr, y = avg_count, fill = plr)) +
  geom_boxplot() +
  facet_grid(~ poss) +
  xlab('Player') +
  ylab('Amount of Faceoffs')
```

```{r}
crutial19 %>%
  ggplot(aes(x = avg_count, y = game)) +
  geom_density()
```

